In [1]:
##Salary

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('salary1.csv')
df.head()

Unnamed: 0  age          Workclass  fnlwgt   education  education-num  \
0           0   39          State-gov   77516   Bachelors             13   
1           1   50   Self-emp-not-inc   83311   Bachelors             13   
2           2   38            Private  215646     HS-grad              9   
3           3   53            Private  234721        11th              7   
4           4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  Income  
0          2174             0              40   United-States       0  
1             0             0              13   United-States       0  
2             0             0              40   United-States       0  
3             0             0              40   United-States       0  
4             0             0              40            Cuba       0

In [4]:
df.isnull().sum()  #to check null values

Unnamed: 0        0
age               0
Workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
Income            0
dtype: int64

In [5]:
df.dtypes   #to check datatypes

Unnamed: 0         int64
age                int64
Workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
Income             int64
dtype: object

In [6]:
df.duplicated().sum()  #to check duplicates

0

In [7]:
df.drop('Unnamed: 0',axis=1,inplace=True) #delete unwanted column

In [8]:
df['Income'].value_counts()

Income
0    778
1    254
Name: count, dtype: int64

In [9]:
df.head()

age          Workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  Income  
0          2174             0              40   United-States       0  
1             0             0              13   United-States       0  
2             0             0              40   United-States       0  
3             0             0              40   United-States       0  
4             0             0              40            Cuba       0

In [10]:
df_num=df.select_dtypes('int64')  #split the dataset as per datatype(int)
df_object=df.select_dtypes('object')  #split the dataset as per datatype(object)

In [11]:
df_num.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   Income  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
df_object.head()

Workclass   education       marital-status          occupation  \
0          State-gov   Bachelors        Never-married        Adm-clerical   
1   Self-emp-not-inc   Bachelors   Married-civ-spouse     Exec-managerial   
2            Private     HS-grad             Divorced   Handlers-cleaners   
3            Private        11th   Married-civ-spouse   Handlers-cleaners   
4            Private   Bachelors   Married-civ-spouse      Prof-specialty   

     relationship    race      sex  native-country  
0   Not-in-family   White     Male   United-States  
1         Husband   White     Male   United-States  
2   Not-in-family   White     Male   United-States  
3         Husband   Black     Male   United-States  
4            Wife   Black   Female            Cuba

In [13]:
#apply LabelEncoder on df_object dataframe

from sklearn.preprocessing import LabelEncoder

In [14]:
for col in df_object.columns:
    le=LabelEncoder() #create the object of Label encoder class
    df_object[col]=le.fit_transform(df_object[col])

In [15]:
df_new=pd.concat([df_num,df_object],axis=1)  #concat df_num and df_object in df_new
df_new.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   Income  Workclass  education  marital-status  occupation  relationship  \
0       0          5          9               4           0             1   
1       0          4          9               2           3             0   
2       0          2         11               0           5             1   
3       0          2          1               2           5             0   
4       0          2          9               2           9             5   

   race  sex  native-country  
0     4    1              28  
1     4    1              28  
2     4    1              28  
3     2    1              28  
4     2    0               4

In [16]:
X=df_new.drop('Income',axis=1) #input column
Y=df_new['Income'] #output

In [17]:
X.columns

Index(['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss',
       'hours-per-week', 'Workclass', 'education', 'marital-status',
       'occupation', 'relationship', 'race', 'sex', 'native-country'],
      dtype='object')

In [18]:
X.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   Workclass  education  marital-status  occupation  relationship  race  sex  \
0          5          9               4           0             1     4    1   
1          4          9               2           3             0     4    1   
2          2         11               0           5             1     4    1   
3          2          1               2           5             0     2    1   
4          2          9               2           9             5     2    0   

   native-country  
0              28  
1              28  
2              28  
3              28  
4               4

In [19]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Income, dtype: int64

In [20]:
X.shape,Y.shape

((1032, 14), (1032,))

In [21]:
#train_test_split

from sklearn.model_selection import train_test_split


In [22]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [23]:
X_train.shape,X_test.shape

((722, 14), (310, 14))

In [24]:
Y_train.shape,Y_test.shape

((722,), (310,))

In [25]:
#apply StandardScaler on Input

from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train) #traingin input
X_test=ss.transform(X_test)#testing input


In [26]:
X_train

array([[-0.25468375,  0.02492289,  0.71924351, ...,  0.39611524,
         0.68372485,  0.25894641],
       [-1.12503586,  3.41142413, -0.51521088, ...,  0.39611524,
         0.68372485,  0.25894641],
       [-1.2832817 ,  0.30211862,  1.13072831, ...,  0.39611524,
         0.68372485,  0.25894641],
       ...,
       [-1.20415878,  0.85337414,  0.30775871, ...,  0.39611524,
         0.68372485,  0.25894641],
       [ 1.72338924, -0.34225413, -0.51521088, ...,  0.39611524,
         0.68372485,  0.25894641],
       [ 0.29917669,  1.04437787, -0.51521088, ..., -3.09163111,
         0.68372485, -6.72086774]])

In [102]:
Y_train.value_counts()

Income
0    540
1    182
Name: count, dtype: int64

In [29]:
#clearly understand,Given data is Unbalance
#0 class : 540 samples and
#1 class : 182 samples
#use RandomOverSampler means to converts minority classes into Majority class means increase means
#make a duplicates copies of some existing record of minority class's sample


In [30]:
#!pip install imblearn

In [31]:
from imblearn.over_sampling import RandomOverSampler
#Create the object of the class RandomOverSampler
ros=RandomOverSampler(random_state=1)


In [32]:
X_train1,Y_train1=ros.fit_resample(X_train,Y_train)
X_train1.shape, Y_train1.shape

((1080, 14), (1080,))

In [33]:
Y_train1.value_counts()

Income
1    540
0    540
Name: count, dtype: int64

In [34]:
#how many sampler of 0's and 1's Y_test.value_counts()
X_test1,Y_test1=ros.fit_resample(X_test,Y_test)
#fit_resample() inbuilt method of RandomOverSampler class

Y_test1.value_counts()

Income
0    238
1    238
Name: count, dtype: int64

In [35]:
X_test1.shape, Y_test1.shape

((476, 14), (476,))

In [36]:
#create user defined function
def create_model(model):
    model.fit(X_train1,Y_train1) #train the model with 70% data
    #test the model with 30% data
    Y_pred=model.predict(X_test1)
    #print confusion matrix
    print(confusion_matrix(Y_test1,Y_pred))
    #generate classification report
    print(classification_report(Y_test1,Y_pred))
    return model

In [37]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [38]:
#perform the model
#call LogisticRegression inbuilt class

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression() #create the object of LogisticRegression class


In [39]:
#call function 

lr=create_model(lr)

[[186  52]
 [ 67 171]]
              precision    recall  f1-score   support

           0       0.74      0.78      0.76       238
           1       0.77      0.72      0.74       238

    accuracy                           0.75       476
   macro avg       0.75      0.75      0.75       476
weighted avg       0.75      0.75      0.75       476



In [40]:
#here f1 score is important in this dataset and f1 score = 0.74 means 74%
#it is good but not better
#reason behind of less socre : model is overfit
#because LogisticRegression cannot select input features automaticaly.

In [41]:
#second Classification Algorithm : DecisionTreeClassifier
#advantages : it can be select input features automatica with the help of Gini and Entropy Method


In [42]:
#DecisionTreeClassifier:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(random_state=1) #creating object of DecisionTreeClassifier class

In [43]:
#call user defined function

dtc=create_model(dtc)

[[205  33]
 [114 124]]
              precision    recall  f1-score   support

           0       0.64      0.86      0.74       238
           1       0.79      0.52      0.63       238

    accuracy                           0.69       476
   macro avg       0.72      0.69      0.68       476
weighted avg       0.72      0.69      0.68       476



In [44]:
#create a DataFrame with the help of Dictionary
dict={'Input column': X.columns, 'IG':dtc.feature_importances_}
df1=pd.DataFrame(dict)
df1

Input column        IG
0              age  0.158889
1           fnlwgt  0.115571
2    education-num  0.153217
3     capital-gain  0.035852
4     capital-loss  0.011485
5   hours-per-week  0.050000
6        Workclass  0.047779
7        education  0.034081
8   marital-status  0.289598
9       occupation  0.056273
10    relationship  0.019118
11            race  0.003453
12             sex  0.012966
13  native-country  0.011717

In [45]:
df1.sort_values(by='IG',ascending=False,ignore_index=True)

Input column        IG
0   marital-status  0.289598
1              age  0.158889
2    education-num  0.153217
3           fnlwgt  0.115571
4       occupation  0.056273
5   hours-per-week  0.050000
6        Workclass  0.047779
7     capital-gain  0.035852
8        education  0.034081
9     relationship  0.019118
10             sex  0.012966
11  native-country  0.011717
12    capital-loss  0.011485
13            race  0.003453

In [46]:
#in decisiontreeclassifier,we got less than score 0.63  means 63% reason behind the less score,model is overfit
#so we reduce overfiting the model, then use pruning technique of DecisionTreeClassifier class
#how to reduce overfitting situation by using the pruning technique:
#  1: max_depth: inbuilt parameter of DecisionTreeClassifier class
#  2.min_samples_leaf: inbuilt parameter of DecisionTreeClassifier class

In [47]:
#Pruning Technique :
#1.max_depth:   2.min_samples_leaf

#1.max_depth:

'''for i in range(1,9):
    dtc1=DecisionTreeClassifier(random_state=1,max_depth=i)
    print("\n Max Depth: ", i)
    dtc1=create_model(dtc1)  #call function'''

'for i in range(1,9):\n    dtc1=DecisionTreeClassifier(random_state=1,max_depth=i)\n    print("\n Max Depth: ", i)\n    dtc1=create_model(dtc1)  #call function'

In [48]:
#create the object of DecisionTreeClassifier class and passing the parameter max_depth=4

dtc1=DecisionTreeClassifier(random_state=1,max_depth=4)
dtc1=create_model(dtc1)  #call function

[[173  65]
 [ 40 198]]
              precision    recall  f1-score   support

           0       0.81      0.73      0.77       238
           1       0.75      0.83      0.79       238

    accuracy                           0.78       476
   macro avg       0.78      0.78      0.78       476
weighted avg       0.78      0.78      0.78       476



In [49]:
#create dictonary
dict={"input columns":X.columns,"IG":dtc1.feature_importances_}
#IG means information gain of each input
df2=pd.DataFrame(dict)
df2.sort_values(by="IG",ascending=False,ignore_index=True)

input columns        IG
0   marital-status  0.536725
1    education-num  0.234955
2              age  0.136568
3   hours-per-week  0.028813
4        Workclass  0.022165
5           fnlwgt  0.018176
6              sex  0.011832
7        education  0.008940
8       occupation  0.001827
9     capital-gain  0.000000
10    capital-loss  0.000000
11    relationship  0.000000
12            race  0.000000
13  native-country  0.000000

In [50]:
#in above report, f1 socre=0.79 means 79% and accuracy = 0.78 means 78%, DecisionTreeClassifier using Gini Index(max depth)

In [51]:
#min_samples_leaf: inbuilt parameter of DecisionTreeClassifier class
#it is second pruning technique,leaf means no child
#value of min_samples_leaf parameter for any dataset >=45 and <=100

'''for i in range(45,101):
    dtc1=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)
    print("\nmin sample leaf : ",i)
    dtc1=create_model(dtc1) #call function'''

'for i in range(45,101):\n    dtc1=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)\n    print("\nmin sample leaf : ",i)\n    dtc1=create_model(dtc1) #call function'

In [52]:
#create the object of DecisionTreeClassifier class and passing the parameter min_samples_leaf=45
dtc1=DecisionTreeClassifier(random_state=1,min_samples_leaf=45)
#call user funtion
dtc1=create_model(dtc1)

[[183  55]
 [ 34 204]]
              precision    recall  f1-score   support

           0       0.84      0.77      0.80       238
           1       0.79      0.86      0.82       238

    accuracy                           0.81       476
   macro avg       0.82      0.81      0.81       476
weighted avg       0.82      0.81      0.81       476



In [53]:
#create DaraFrame with help of dictionary
dict={"Input columns":X.columns,"IG":dtc1.feature_importances_}
#IG means informations gain of each input
df2=pd.DataFrame(dict)
df2.sort_values(by="IG",ascending=False,ignore_index=True)

Input columns        IG
0   marital-status  0.569262
1    education-num  0.262006
2              age  0.128585
3   hours-per-week  0.012915
4           fnlwgt  0.010877
5       occupation  0.010251
6     capital-gain  0.006102
7     capital-loss  0.000000
8        Workclass  0.000000
9        education  0.000000
10    relationship  0.000000
11            race  0.000000
12             sex  0.000000
13  native-country  0.000000

In [54]:
#in above report, f1 socre=0.82 means 82% and accuracy = 0.81 means 81%, DecisionTreeClassifier using Gini Index(min samples leaf)

In [55]:
#Entrophy:
#use entropy method
#create object
dtc1=DecisionTreeClassifier(random_state=1,criterion='entropy')

In [56]:
#call function
dtc1=create_model(dtc1)

[[210  28]
 [ 97 141]]
              precision    recall  f1-score   support

           0       0.68      0.88      0.77       238
           1       0.83      0.59      0.69       238

    accuracy                           0.74       476
   macro avg       0.76      0.74      0.73       476
weighted avg       0.76      0.74      0.73       476



In [57]:
#create a df 
dict={'input columns':X.columns,'IG':dtc.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by='IG',ascending=False,ignore_index=True)

input columns        IG
0   marital-status  0.289598
1              age  0.158889
2    education-num  0.153217
3           fnlwgt  0.115571
4       occupation  0.056273
5   hours-per-week  0.050000
6        Workclass  0.047779
7     capital-gain  0.035852
8        education  0.034081
9     relationship  0.019118
10             sex  0.012966
11  native-country  0.011717
12    capital-loss  0.011485
13            race  0.003453

In [58]:
#in decisiontreeclassifier,we got less  score0.69 means 69% reason behind the less score,model is overfit
#so we reduce overfiting the model, then use pruning technique of DecisionTreeClassifier class
#how to reduce overfitting situation by using the pruning technique:
#  1: max_dept: inbuilt parameter of DecisionTreeClassifier class
#  2.min_samples_leaf: inbuilt parameter of DecisionTreeClassifier class

In [59]:
#Entropy
#max_depth:inbuilt parameter of DecisionTreeClassifier
#DecisionTreeClassifier class
#value of max_depth parameter for any dataset <=8
'''for i in range(1,9):
    #create object DecisionTreeClassifier class and passing parameter max_depth and 
    #criterion="entropy"
    dtc1=DecisionTreeClassifier(random_state=1,criterion="entropy",max_depth=i)
    print("\nmax_depth:",i)
    #call user difined funtion
    dtc1=create_model(dtc1)'''

'for i in range(1,9):\n    #create object DecisionTreeClassifier class and passing parameter max_depth and \n    #criterion="entropy"\n    dtc1=DecisionTreeClassifier(random_state=1,criterion="entropy",max_depth=i)\n    print("\nmax_depth:",i)\n    #call user difined funtion\n    dtc1=create_model(dtc1)'

In [60]:
#create the object of DecisionTreeClassifier class and passing the parameter max_depth=4
dtc1=DecisionTreeClassifier(random_state=1,criterion='entropy',max_depth=4)
#call user difined function
dtc1=create_model(dtc1)

[[162  76]
 [ 22 216]]
              precision    recall  f1-score   support

           0       0.88      0.68      0.77       238
           1       0.74      0.91      0.82       238

    accuracy                           0.79       476
   macro avg       0.81      0.79      0.79       476
weighted avg       0.81      0.79      0.79       476



In [61]:
#create DataFrame with help of dictionary
dict={"input columns":X.columns,"IG":dtc1.feature_importances_}
df2=pd.DataFrame(dict)
df2.sort_values(by="IG",ascending=False,ignore_index=True)

input columns        IG
0   marital-status  0.479199
1    education-num  0.269734
2              age  0.120329
3           fnlwgt  0.045122
4   hours-per-week  0.040514
5     capital-gain  0.019361
6             race  0.017366
7       occupation  0.008373
8     capital-loss  0.000000
9        Workclass  0.000000
10       education  0.000000
11    relationship  0.000000
12             sex  0.000000
13  native-country  0.000000

In [62]:
#In about Report, f1 score=0.82 means 82% and Accuracy=0.79 
#DecisionTreeclasifier using Entropy (max_depth)

In [63]:
#Entropy
#min_samples_leaf: inbuilt parameter of DecisionTreeClassifier
#value of min_samples_leaf >=45 and <=100 
'''for i in range(45,101): #i=45 i<100 i=i+1
    #create object DecisionTreeClassifier passing parameter min_samples_leaf and criterion="entropy"
    dtc1=DecisionTreeClassifier(random_state=1,criterion="entropy",min_samples_leaf=i)
    print('\nmin_leaf_samples:',i)
    #call user difined function
    dtc1=create_model(dtc1)'''

'for i in range(45,101): #i=45 i<100 i=i+1\n    #create object DecisionTreeClassifier passing parameter min_samples_leaf and criterion="entropy"\n    dtc1=DecisionTreeClassifier(random_state=1,criterion="entropy",min_samples_leaf=i)\n    print(\'\nmin_leaf_samples:\',i)\n    #call user difined function\n    dtc1=create_model(dtc1)'

In [64]:
#create object DecisionTreeClassifier and passing parameter min_samples_leaf = 45
#and criterion="entropy"
dtc1=DecisionTreeClassifier(random_state=1,criterion="entropy",min_samples_leaf=45)
#call user difined function
dtc1=create_model(dtc1)

[[182  56]
 [ 34 204]]
              precision    recall  f1-score   support

           0       0.84      0.76      0.80       238
           1       0.78      0.86      0.82       238

    accuracy                           0.81       476
   macro avg       0.81      0.81      0.81       476
weighted avg       0.81      0.81      0.81       476



In [65]:
#create DataFrame with help of DataFrame
dict={"input columns":X.columns,"IG":dtc1.feature_importances_}
#IG means informations gain of each input
df2=pd.DataFrame(dict)
df2.sort_values(by="IG",ascending=False,ignore_index=True)

input columns        IG
0   marital-status  0.480437
1    education-num  0.289239
2              age  0.142991
3     capital-gain  0.060516
4   hours-per-week  0.014320
5           fnlwgt  0.006424
6       occupation  0.006075
7     capital-loss  0.000000
8        Workclass  0.000000
9        education  0.000000
10    relationship  0.000000
11            race  0.000000
12             sex  0.000000
13  native-country  0.000000

In [66]:
#In about Report, f1 score=0.82 means 82% and Accuracy=0.81
#DecisionTreeclasifier using Entropy (min_samples_leaf)

In [67]:
#Apply Ensembling Technique
#1, Bootstraping method:
#randomForestTree(use Bagging):-
from sklearn.ensemble import RandomForestClassifier

In [68]:
#RandomForestClassifier inbuilt inner class: passing the parameter
#NO.of decisiontree>=10 and <=100
#No. of Decisiontrees : use inbuilt parameter n_estimators
'''for i in range(10,101): #starti=1 i<100 step i=i+1
    #create object of RandomForestClassifier class
    rfc=RandomForestClassifier(n_estimators=i,random_state=1)
    print("No. of Estimators mean No. of Defcision Tree:",i)
    #call function
    rfc=create_model(rfc)'''

'for i in range(10,101): #starti=1 i<100 step i=i+1\n    #create object of RandomForestClassifier class\n    rfc=RandomForestClassifier(n_estimators=i,random_state=1)\n    print("No. of Estimators mean No. of Defcision Tree:",i)\n    #call function\n    rfc=create_model(rfc)'

In [69]:
#create object of RandomForestClassifier class
rfc=RandomForestClassifier(n_estimators=17,random_state=1)
#call user defined funtion
rfc=create_model(rfc)

[[215  23]
 [ 75 163]]
              precision    recall  f1-score   support

           0       0.74      0.90      0.81       238
           1       0.88      0.68      0.77       238

    accuracy                           0.79       476
   macro avg       0.81      0.79      0.79       476
weighted avg       0.81      0.79      0.79       476



In [70]:
#create a dataframe with the help of dictionary
dict={"Input columns":X.columns,"IG":rfc.feature_importances_} #we replace the dtc1 with the rfc
#IG means information gain of each input
df2=pd.DataFrame(dict)
df2.sort_values(by="IG",ascending=False,ignore_index=True) 

Input columns        IG
0              age  0.159669
1   marital-status  0.144491
2    education-num  0.131724
3           fnlwgt  0.116899
4     relationship  0.097614
5   hours-per-week  0.091244
6       occupation  0.058792
7        education  0.050051
8     capital-gain  0.045912
9        Workclass  0.043522
10            race  0.019109
11  native-country  0.013943
12             sex  0.013595
13    capital-loss  0.013433

In [71]:
#In about Report, f1 score=0.77 means 77% and Accuracy=0.79
#RandomforestTreeClassifier

In [72]:
#Apply next Ensembling Technique on same dataset
#ADA Boost
#inbuilt class AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

In [73]:
#create the object AdaBoostClassifier and passing the value
'''for i in range(1,17):
    #create the object of AdaBoostClassifier
    ada=AdaBoostClassifier(n_estimators=i,random_state=1)
    print("No of Estimators:",i)
    #call user defined funtion
    ada=create_model(ada)'''

'for i in range(1,17):\n    #create the object of AdaBoostClassifier\n    ada=AdaBoostClassifier(n_estimators=i,random_state=1)\n    print("No of Estimators:",i)\n    #call user defined funtion\n    ada=create_model(ada)'

In [74]:
#create object AdaBoostClassifier
ada=AdaBoostClassifier(n_estimators=9,random_state=1)
#call user defined funtion
ada=create_model(ada)

[[183  55]
 [ 38 200]]
              precision    recall  f1-score   support

           0       0.83      0.77      0.80       238
           1       0.78      0.84      0.81       238

    accuracy                           0.80       476
   macro avg       0.81      0.80      0.80       476
weighted avg       0.81      0.80      0.80       476



In [75]:
#create dataframe with the help of dictionary
dict={"input columns":X.columns,"IG":ada.feature_importances_}
#IG means information gain of each input
df2=pd.DataFrame(dict)
df2.sort_values(by="IG",ascending=False,ignore_index=True)

input columns        IG
0    education-num  0.222222
1   marital-status  0.222222
2              age  0.111111
3     capital-gain  0.111111
4     capital-loss  0.111111
5   hours-per-week  0.111111
6        Workclass  0.111111
7           fnlwgt  0.000000
8        education  0.000000
9       occupation  0.000000
10    relationship  0.000000
11            race  0.000000
12             sex  0.000000
13  native-country  0.000000

In [76]:
#In about Report, f1 score=0.81 means 81% and Accuracy=0.80 means 80%
#AdaBoostClassifier 

In [77]:
#Gradient Boosting(Gb) 
#inbuilt class GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [78]:
#use inbuilt parameter of GradienBoostingClassifier Class
'''for i in range(10,101):
    #create object GradientBoostingClassifier passing the value
    gbc=GradientBoostingClassifier(n_estimators=i,random_state=i)
    print("No of Estimators:",i)
    #call user defined function
    gbc=create_model(gbc)'''

'for i in range(10,101):\n    #create object GradientBoostingClassifier passing the value\n    gbc=GradientBoostingClassifier(n_estimators=i,random_state=i)\n    print("No of Estimators:",i)\n    #call user defined function\n    gbc=create_model(gbc)'

In [79]:
#create the object GradientBoostingClassifier 
gbc=GradientBoostingClassifier(n_estimators=11,random_state=1)
#call the user defined function
gbc=create_model(gbc)

[[174  64]
 [ 35 203]]
              precision    recall  f1-score   support

           0       0.83      0.73      0.78       238
           1       0.76      0.85      0.80       238

    accuracy                           0.79       476
   macro avg       0.80      0.79      0.79       476
weighted avg       0.80      0.79      0.79       476



In [80]:
#create a dataframe with help of dictionary
dict={"input columns":X.columns,"IG":gbc.feature_importances_}
df2=pd.DataFrame(dict)
df2.sort_values(by="IG",ascending=False,ignore_index=True)

input columns        IG
0   marital-status  0.519187
1    education-num  0.252376
2              age  0.083183
3     capital-gain  0.040331
4   hours-per-week  0.039589
5        education  0.023834
6     relationship  0.022262
7   native-country  0.009123
8           fnlwgt  0.007440
9              sex  0.002675
10    capital-loss  0.000000
11       Workclass  0.000000
12      occupation  0.000000
13            race  0.000000

In [81]:
#In about Report, f1 score=0.80 means 80% and Accuracy=0.79 means 79%
#GradientBoostingClassifier

In [82]:
#Extreme Gradient Boosting(XGB)
#inbuilt class XGBclassifier--> define in inbuilt package xgboost of 
#python
#first install xgboost package with the help of pip on your
#system
!pip install xgboost

In [83]:
#call XGBClassifier class
from xgboost import XGBClassifier

In [84]:
#call XGBclassifier class
'''for i in range(10,101):
    #create object xgb and passing the vlaue of parameter
    xgb=XGBClassifier(n_estimators=i,reg_alpha=1,random_state=1)
    print("No of Estimators:",i)
    #call funtion
    xgb=create_model(xgb)'''

'for i in range(10,101):\n    #create object xgb and passing the vlaue of parameter\n    xgb=XGBClassifier(n_estimators=i,reg_alpha=1,random_state=1)\n    print("No of Estimators:",i)\n    #call funtion\n    xgb=create_model(xgb)'

In [85]:
#create the object XGBclasifier
xgb=XGBClassifier(n_estimators=12,reg_alpha=1,random_state=1)
#call user defined funtion
xgb=create_model(xgb)

[[199  39]
 [ 46 192]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.82       238
           1       0.83      0.81      0.82       238

    accuracy                           0.82       476
   macro avg       0.82      0.82      0.82       476
weighted avg       0.82      0.82      0.82       476



In [86]:
#create a dataframe with help of dictionary
dict={"input columns":X.columns,"IG":xgb.feature_importances_}
df2=pd.DataFrame(dict)
df2.sort_values(by="IG",ascending=False,ignore_index=True)

input columns        IG
0   marital-status  0.411045
1    education-num  0.131606
2     capital-gain  0.084247
3              age  0.057984
4   hours-per-week  0.044663
5     capital-loss  0.037838
6     relationship  0.035035
7   native-country  0.034790
8        education  0.034156
9       occupation  0.027572
10          fnlwgt  0.027104
11       Workclass  0.026388
12             sex  0.024280
13            race  0.023291

In [87]:
#In about Report, f1 score=0.82 means 82% and Accuracy=0.82 means 82%
#XGBclassifier

In [88]:
#support vector machine


In [89]:
#1 use linear kernel function
# Linear kernel fucntion
#use of LinearSVC
#call inbuilt class LinearSVC
from sklearn.svm import LinearSVC

In [90]:
#create object of linearSVC class
svc=LinearSVC(random_state=1) #Hard Margin bydefault

In [91]:
#call function (user defined function)
svc=create_model(svc)

[[184  54]
 [ 61 177]]
              precision    recall  f1-score   support

           0       0.75      0.77      0.76       238
           1       0.77      0.74      0.75       238

    accuracy                           0.76       476
   macro avg       0.76      0.76      0.76       476
weighted avg       0.76      0.76      0.76       476



In [92]:
#In about Report, f1 score=0.75 means 75% and Accuracy=0.76 means 76%
#LinearSVG(Hard Margin)
#

In [93]:
#Here score is not good , not better
#behind the reason, may be model is overfit.
#means both classes are separate with straight line but may be model is 
#overfit, so reduced overfit of model, we add external error on training
#time and this processis known as soft margin
#create the object of class LinearSVC
svc1= LinearSVC(random_state=1,C=0.0001) #if error value is not works means data will not seprate linearly 
#C inbuilt parameter of LinearSVC class and value of these parameter
#betweeen >0-1 
#correct value-=0.0001

In [94]:
#call functions defined function
svc=create_model(svc)

[[184  54]
 [ 61 177]]
              precision    recall  f1-score   support

           0       0.75      0.77      0.76       238
           1       0.77      0.74      0.75       238

    accuracy                           0.76       476
   macro avg       0.76      0.76      0.76       476
weighted avg       0.76      0.76      0.76       476



In [95]:
#In above report, f1 score = 0.75 means 75% and Accuracy = 0.76 means 76%, LinearSVC(soft margin)

In [96]:
#no.changes in score when add external error on training time 
#means data is non-linear data.
#use Non Linear kernal function: 2. polynomial kernal function
# polynomial kernel function:
'''it increase the dimension means its converts low dimension to high dimension.
suppose we have 1D  then it convert into 2D and so on.
use inbuilt class svc for non linear kernal function : polynomial or radial basis kernal function'''

from sklearn.svm import SVC
#create object of SVC class and pass the parameter kernel="poly"
poly_SVC=SVC(random_state=1,kernel="poly") #Poly means polynomial


In [97]:
#call user defined function
poly_SVC=create_model(poly_SVC)

[[215  23]
 [104 134]]
              precision    recall  f1-score   support

           0       0.67      0.90      0.77       238
           1       0.85      0.56      0.68       238

    accuracy                           0.73       476
   macro avg       0.76      0.73      0.73       476
weighted avg       0.76      0.73      0.73       476



In [98]:
#In about Report, f1 score=0.68 means 68% and Accuracy=0.73 means 73%
#LinearSVG
#SVC(kernel="poly")

In [99]:
#create object of SVC for radial basis
svc_radial=SVC(random_state=1,kernel="rbf")
#rbf means radial basis function
#call user defined funtion
svc_radical=create_model(svc_radial)

[[199  39]
 [ 69 169]]
              precision    recall  f1-score   support

           0       0.74      0.84      0.79       238
           1       0.81      0.71      0.76       238

    accuracy                           0.77       476
   macro avg       0.78      0.77      0.77       476
weighted avg       0.78      0.77      0.77       476



In [100]:
#In above report, f1 score = 0.76 means 76% and Accuracy = 0.77 means 77%, SVC(Radial basis function)

In [101]:
#In this dataset, we got best score by Extreme Gradient Boost.
#f1 socre=0.82 means 82% and accuracy = 0.82 means 82%