In [1]:
import pickle

In [2]:
#To read file in read binary mode

#to open file in read mode for model
file1=open("model.pkl","rb")



In [3]:
#to open file in read mode for scale
file2=open("scale.pkl","rb")

In [4]:
#to open file in read mode for model
file3=open("label.pkl","rb")

In [5]:
#to read data from file1 hold in temp object
model=pickle.load(file1)  #load() inbuilt method of pickle class


In [6]:
#to read data from file2 hold in temp object
scale=pickle.load(file2)  #load() inbuilt method of pickle class


In [7]:
#to read data from file3 hold in temp object
label=pickle.load(file3)  #load() inbuilt method of pickle class


In [8]:
###### input
age=int(input("Enter Age of Client"))
job=input("Enter Job :")
marital = input("Enter Marital Status of client")
education=input("Enter education of client")
default =input("has credit in default(yes/ no)")
housing=input("has housing loan? ")
loan=input("has personal loan? ")
contact = input("contact communication type ('cellular','telephone')")
month = input("last contact month of year ('jan', 'feb', 'mar', …, 'nov', 'dec')")
day_of_week=input("last contact day of the week ('mon','tue','wed','thu','fri')")
duration= int(input("last contact duration, in seconds (numeric)"))
campaign=int(input("number of contacts performed during this campaign and for this client"))
pdays=int(input("number of days that passed by after the client was last contacted from a previous campaign"))
previous=int(input(" number of contacts performed before this campaign and for this client"))
poutcome=input("outcome of the previous marketing campaign ('failure','nonexistent','success')")
emp_var_rate=float(input("employment variation rate - quarterly indicator"))
cons_price_idx=float(input("consumer price index - monthly indicator "))
cons_conf_idx=float(input("consumer confidence index - monthly indicator"))
euribor3m=float(input("euribor 3 month rate - daily indicator"))
nr_employed=float(input("number of employees - quarterly indicator"))



Enter Age of Client 56
Enter Job : housemaid
Enter Marital Status of client married
Enter education of client basic.4y
has credit in default(yes/ no) no
has housing loan?  no
has personal loan?  no
contact communication type ('cellular','telephone') telephone
last contact month of year ('jan', 'feb', 'mar', …, 'nov', 'dec') may
last contact day of the week ('mon','tue','wed','thu','fri') mon
last contact duration, in seconds (numeric) 261
number of contacts performed during this campaign and for this client 1
number of days that passed by after the client was last contacted from a previous campaign 999
 number of contacts performed before this campaign and for this client 0
outcome of the previous marketing campaign ('failure','nonexistent','success') nonexistent
employment variation rate - quarterly indicator 1.1
consumer price index - monthly indicator  93.994
consumer confidence index - monthly indicator -36.4
euribor 3 month rate - daily indicator 4.857
number of employees - quarte

In [22]:
# split the object and number and store in variable.
obj=[job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome]
num=[age,duration,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed]


In [23]:
# create a numpy array
import numpy as np
obj=np.array(obj)


In [24]:
type(obj),obj.ndim # check the type and dimension of object.

(numpy.ndarray, 1)

In [25]:
obj

array(['housemaid', 'married', 'basic.4y', 'no', 'no', 'no', 'telephone',
       'may', 'mon', 'nonexistent'], dtype='<U11')

In [26]:
obj=label.fit_transform(obj) #to apply labelencoder on object

In [27]:
obj

array([1, 2, 0, 5, 5, 5, 7, 3, 4, 6], dtype=int64)

In [28]:
obj=[obj]

In [16]:
num=np.array([num]) # Create a numpy array

In [17]:
X1=np.concatenate([obj,num],axis=1) # concatenate object and number.

In [18]:
X1

array([[ 1.0000e+00,  2.0000e+00,  0.0000e+00,  5.0000e+00,  5.0000e+00,
         5.0000e+00,  7.0000e+00,  3.0000e+00,  4.0000e+00,  6.0000e+00,
         5.6000e+01,  2.6100e+02,  1.0000e+00,  9.9900e+02,  0.0000e+00,
         1.1000e+00,  9.3994e+01, -3.6400e+01,  4.8570e+00,  5.1910e+03]])

In [19]:
X_final=scale.transform(X1) #Apply Scaling

C:\Users\swapn\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [20]:
X_final

array([[-1.02236484e+00,  1.37328671e+00, -1.98197352e+00,
         6.00231206e+02,  8.94533376e+00,  1.34773308e+01,
         1.37754408e+01, -5.34576050e-01,  1.43340435e+00,
         1.39515950e+01,  1.54198010e+00,  1.26043309e-02,
        -5.71597049e-01,  1.94636552e-01, -3.51355856e-01,
         6.49026332e-01,  7.26539834e-01,  8.85310598e-01,
         7.13055479e-01,  3.31627225e-01]])

In [21]:
# Predict the model
Y_pred=model.predict(X_final)
print(Y_pred)

[0]
