In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('bank_1.csv', sep=';')   #to load dataset
df.head() #to check first five records

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [3]:
df.isnull().sum()  #to check null values

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [4]:
df.dtypes  #to check datatype

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [5]:
df.shape

(41188, 21)

In [6]:
df['y'].value_counts()

y
no     36548
yes     4640
Name: count, dtype: int64

In [7]:
df['age'].value_counts()

age
31    1947
32    1846
33    1833
36    1780
35    1759
      ... 
89       2
91       2
94       1
87       1
95       1
Name: count, Length: 78, dtype: int64

In [8]:
df['job'].value_counts()

job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

In [9]:
df['marital'].value_counts()

marital
married     24928
single      11568
divorced     4612
unknown        80
Name: count, dtype: int64

In [10]:
df['education'].value_counts()

education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: count, dtype: int64

In [11]:
df['default'].value_counts()

default
no         32588
unknown     8597
yes            3
Name: count, dtype: int64

In [12]:
df['housing'].value_counts()

housing
yes        21576
no         18622
unknown      990
Name: count, dtype: int64

In [13]:
df['housing'].value_counts()

housing
yes        21576
no         18622
unknown      990
Name: count, dtype: int64

In [14]:
df['loan'].value_counts()

loan
no         33950
yes         6248
unknown      990
Name: count, dtype: int64

In [15]:
df['contact'].value_counts()

contact
cellular     26144
telephone    15044
Name: count, dtype: int64

In [16]:
df['month'].value_counts()

month
may    13769
jul     7174
aug     6178
jun     5318
nov     4101
apr     2632
oct      718
sep      570
mar      546
dec      182
Name: count, dtype: int64

In [17]:
df['day_of_week'].value_counts()

day_of_week
thu    8623
mon    8514
wed    8134
tue    8090
fri    7827
Name: count, dtype: int64

In [18]:
df['duration'].value_counts()

duration
90      170
85      170
136     168
73      167
124     164
       ... 
1569      1
1053      1
1263      1
1169      1
1868      1
Name: count, Length: 1544, dtype: int64

In [19]:
df['campaign'].value_counts()

campaign
1     17642
2     10570
3      5341
4      2651
5      1599
6       979
7       629
8       400
9       283
10      225
11      177
12      125
13       92
14       69
17       58
16       51
15       51
18       33
20       30
19       26
21       24
22       17
23       16
24       15
27       11
29       10
28        8
26        8
25        8
31        7
30        7
35        5
32        4
33        4
34        3
42        2
40        2
43        2
56        1
39        1
41        1
37        1
Name: count, dtype: int64

In [20]:
df['pdays'].value_counts()

pdays
999    39673
3        439
6        412
4        118
9         64
2         61
7         60
12        58
10        52
5         46
13        36
11        28
1         26
15        24
14        20
8         18
0         15
16        11
17         8
18         7
22         3
19         3
21         2
25         1
26         1
27         1
20         1
Name: count, dtype: int64

In [21]:
df['previous'].value_counts()

previous
0    35563
1     4561
2      754
3      216
4       70
5       18
6        5
7        1
Name: count, dtype: int64

In [22]:
df['poutcome'].value_counts()

poutcome
nonexistent    35563
failure         4252
success         1373
Name: count, dtype: int64

In [23]:
df['emp.var.rate'].value_counts()

emp.var.rate
 1.4    16234
-1.8     9184
 1.1     7763
-0.1     3683
-2.9     1663
-3.4     1071
-1.7      773
-1.1      635
-3.0      172
-0.2       10
Name: count, dtype: int64

In [24]:
df['cons.price.idx'].value_counts()

cons.price.idx
93.994    7763
93.918    6685
92.893    5794
93.444    5175
94.465    4374
93.200    3616
93.075    2458
92.201     770
92.963     715
92.431     447
92.649     357
94.215     311
94.199     303
92.843     282
92.379     267
93.369     264
94.027     233
94.055     229
93.876     212
94.601     204
92.469     178
93.749     174
92.713     172
94.767     128
93.798      67
92.756      10
Name: count, dtype: int64

In [25]:
df['cons.conf.idx'].value_counts()

cons.conf.idx
-36.4    7763
-42.7    6685
-46.2    5794
-36.1    5175
-41.8    4374
-42.0    3616
-47.1    2458
-31.4     770
-40.8     715
-26.9     447
-30.1     357
-40.3     311
-37.5     303
-50.0     282
-29.8     267
-34.8     264
-38.3     233
-39.8     229
-40.0     212
-49.5     204
-33.6     178
-34.6     174
-33.0     172
-50.8     128
-40.4      67
-45.9      10
Name: count, dtype: int64

In [26]:
df['euribor3m'].value_counts()

euribor3m
4.857    2868
4.962    2613
4.963    2487
4.961    1902
4.856    1210
         ... 
3.853       1
3.901       1
0.969       1
0.956       1
3.669       1
Name: count, Length: 316, dtype: int64

In [27]:
df['nr.employed'].value_counts()

nr.employed
5228.1    16234
5099.1     8534
5191.0     7763
5195.8     3683
5076.2     1663
5017.5     1071
4991.6      773
5008.7      650
4963.6      635
5023.5      172
5176.3       10
Name: count, dtype: int64

In [28]:
df['marital'].replace('unknown',np.nan,inplace=True)   #replace unknown value with np.nan
m=df['marital'].mode()
print(m)


0    married
Name: marital, dtype: object


In [29]:
df['marital'].fillna('married',inplace=True)  #fill nan with mode

In [30]:
df['education'].replace('unknown','Others',inplace=True)   #replace unknown value with Others

In [31]:
df['default'].replace('unknown',np.nan,inplace=True)   #replace unknown value with np.nan
m=df['default'].mode()
print(m)


0    no
Name: default, dtype: object


In [32]:
df['default'].fillna('no',inplace=True)   #fill nan with mode

In [33]:
df['housing'].replace('unknown',np.nan,inplace=True)   #replace unknown value with np.nan
m=df['housing'].mode()
print(m)


0    yes
Name: housing, dtype: object


In [34]:
df['housing'].fillna('yes',inplace=True)   #fill nan with mode

In [35]:
df['loan'].replace('unknown',np.nan,inplace=True)   #replace unknown value with np.nan
m=df['loan'].mode()
print(m)


0    no
Name: loan, dtype: object


In [36]:
df['loan'].fillna('no',inplace=True)

In [37]:
df['job'].replace('unknown','Others',inplace=True)   #replace unknown value with Others

In [38]:
df.isnull().sum() #once again checking null values

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [39]:
df.duplicated().sum()    #checking duplicate value in dataset

14

In [40]:
df.drop_duplicates(inplace=True)  #dropping the duplicate value from dataset

In [41]:
df_object=df.select_dtypes('object')   #to take object type data in df_object

In [42]:
df_num=df.select_dtypes(['int64','float64'])  #to take int and float type data in df_num

In [43]:
from sklearn.preprocessing import LabelEncoder    
for col in df_object:   #applying for loop to apply LabelEncoder to each column of df_object dataframe
    le=LabelEncoder()
    df_object[col]=le.fit_transform(df_object[col])

In [44]:
df_object['job'].dtypes

dtype('int32')

In [45]:
df_new=pd.concat([df_object,df_num],axis=1)   #concating the 2 dataframes.
df_new.head()

job  marital  education  default  housing  loan  contact  month  \
0    4        1          1        0        0     0        1      6   
1    8        1          4        0        0     0        1      6   
2    8        1          4        0        1     0        1      6   
3    1        1          2        0        0     0        1      6   
4    8        1          4        0        0     1        1      6   

   day_of_week  poutcome  ...  age  duration  campaign  pdays  previous  \
0            1         1  ...   56       261         1    999         0   
1            1         1  ...   57       149         1    999         0   
2            1         1  ...   37       226         1    999         0   
3            1         1  ...   40       151         1    999         0   
4            1         1  ...   56       307         1    999         0   

   emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed  
0           1.1          93.994          -36.4      4.857       5191.0  
1           1.1          93.994          -36.4      4.857       5191.0  
2           1.1          93.994          -36.4      4.857       5191.0  
3           1.1          93.994          -36.4      4.857       5191.0  
4           1.1          93.994          -36.4      4.857       5191.0  

[5 rows x 21 columns]

In [46]:
X=df_new.drop('y',axis=1)  #input columns
Y=df_new['y']   #output column

In [47]:
#apply train test split

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [48]:
#apply standarscaler:

from sklearn.preprocessing import StandardScaler
ss=StandardScaler()  #creating object of StandardScaler Class

In [49]:
X_train=ss.fit_transform(X_train)  #applying scaling on training input X_train
X_test=ss.transform(X_test)   #applying scaling on testing input X_test

In [50]:
Y_train.value_counts()

y
0    25618
1     3203
Name: count, dtype: int64

In [51]:
#clearly understand, Given data is unbalance 
#Use RandomOverSampler means to converts minority classes into majority class means increase make
#a duplicates copies of some existing record of minority class's sample

In [52]:
#!pip install imblearn

from imblearn.over_sampling import RandomOverSampler

#Create the object of the class RandomOverSampler
ros=RandomOverSampler(random_state=1)

In [53]:
X_train1,Y_train1=ros.fit_resample(X_train,Y_train)
X_train1.shape, Y_train1.shape

((51236, 20), (51236,))

In [54]:
Y_train1.value_counts()

y
0    25618
1    25618
Name: count, dtype: int64

In [55]:
#how many sampler of 0's and 1's Y_test.value_counts()
X_test1,Y_test1=ros.fit_resample(X_test,Y_test)
#fit_resample() inbuilt method of RandomOverSampler class

Y_test1.value_counts()

y
1    10917
0    10917
Name: count, dtype: int64

In [56]:
X_test1.shape, Y_test1.shape

((21834, 20), (21834,))

In [57]:
#create user defined function
def create_model(model):
    model.fit(X_train1,Y_train1) #train the model with 70% data
    #test the model with 30% data
    Y_pred=model.predict(X_test1)
    #print confusion matrix
    print(confusion_matrix(Y_test1,Y_pred))
    #generate classification report
    print(classification_report(Y_test1,Y_pred))
    return model

In [58]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report



In [59]:
#perform the model
#1.LogisticRegression
#call logistic regression inbuilt class
from sklearn.linear_model import LogisticRegression

In [60]:
lr=LogisticRegression()   #create the object of LogisticRegression Class

In [61]:
#call function 
lr=create_model(lr)

[[9282 1635]
 [1394 9523]]
              precision    recall  f1-score   support

           0       0.87      0.85      0.86     10917
           1       0.85      0.87      0.86     10917

    accuracy                           0.86     21834
   macro avg       0.86      0.86      0.86     21834
weighted avg       0.86      0.86      0.86     21834



In [62]:
#here recall score is important in this dataset and recall score = 0.87 means 87%
#it is good but not better
#reason behind of less socre : model is overfit
#because LogisticRegression cannot select input features automaticaly.

In [63]:
#second Classification Algorithm : DecisionTreeClassifier
#advantages : it can be select input features automatica with the help of Gini and Entropy Method


In [64]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
dtc=DecisionTreeClassifier(random_state=1)

In [66]:
#call user defined function
dtc=create_model(dtc)

[[10318   599]
 [ 5348  5569]]
              precision    recall  f1-score   support

           0       0.66      0.95      0.78     10917
           1       0.90      0.51      0.65     10917

    accuracy                           0.73     21834
   macro avg       0.78      0.73      0.71     21834
weighted avg       0.78      0.73      0.71     21834



In [67]:
#create a df 
dict={'input columns':X.columns,'IG':dtc.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by='IG',ascending=False,ignore_index=True)

input columns        IG
0         duration  0.440809
1      nr.employed  0.177071
2        euribor3m  0.074209
3              age  0.063784
4     emp.var.rate  0.038670
5    cons.conf.idx  0.030706
6      day_of_week  0.026089
7              job  0.023265
8        education  0.022763
9         campaign  0.021767
10           month  0.018673
11         marital  0.011119
12         housing  0.011050
13           pdays  0.010653
14  cons.price.idx  0.009403
15        previous  0.007196
16            loan  0.005444
17         contact  0.004051
18        poutcome  0.003277
19         default  0.000000

In [68]:
#in decisiontreeclassifier,we got less than score0.51 means 51% reason behind the less score,model is overfit
#so we reduce overfiting the model, then use pruning technique of DecisionTreeClassifier class
#how to reduce overfitting situation by using the pruning technique:
#  1: max_dept: inbuilt parameter of DecisionTreeClassifier class
#  2.min_samples_leaf: inbuilt parameter of DecisionTreeClassifier class

In [69]:
#max_dept: inbuilt parameter of DecisionTreeClassifier class
#value of max_depth parameter for any dataset<=8
'''for i in range (1,9): #start=1 stop=9-1=8 step=+1
    #create object of DecisionTreeClassifier class and passing the parametrer max_dept
    dtc1=DecisionTreeClassifier(random_state=1,max_depth=i)
    #i=1 then i=2 etc
    #by default use method gini index
    print("\nMax depth: ",i)
    #call user defined function
    dtc1=create_model(dtc1)'''

'for i in range (1,9): #start=1 stop=9-1=8 step=+1\n    #create object of DecisionTreeClassifier class and passing the parametrer max_dept\n    dtc1=DecisionTreeClassifier(random_state=1,max_depth=i)\n    #i=1 then i=2 etc\n    #by default use method gini index\n    print("\nMax depth: ",i)\n    #call user defined function\n    dtc1=create_model(dtc1)'

In [70]:
#create the object of DecisionTreeClassifier class and passing the parameter max_depth=5
dtc1=DecisionTreeClassifier(random_state=1,max_depth=5)
#by default use method gini index
#call user defined function
dtc1=create_model(dtc1)

[[ 9009  1908]
 [  784 10133]]
              precision    recall  f1-score   support

           0       0.92      0.83      0.87     10917
           1       0.84      0.93      0.88     10917

    accuracy                           0.88     21834
   macro avg       0.88      0.88      0.88     21834
weighted avg       0.88      0.88      0.88     21834



In [71]:
#create a df 
dict={'input columns':X.columns,'IG':dtc1.feature_importances_}   #IG means information gain of each input
df1=pd.DataFrame(dict)
df1.sort_values(by='IG',ascending=False,ignore_index=True)

input columns        IG
0         duration  0.564365
1      nr.employed  0.332387
2    cons.conf.idx  0.039068
3        euribor3m  0.025338
4            month  0.021158
5            pdays  0.013639
6   cons.price.idx  0.003561
7         previous  0.000367
8         campaign  0.000116
9     emp.var.rate  0.000000
10             job  0.000000
11         marital  0.000000
12        poutcome  0.000000
13     day_of_week  0.000000
14         contact  0.000000
15            loan  0.000000
16         housing  0.000000
17         default  0.000000
18       education  0.000000
19             age  0.000000

In [72]:
#in above report, recall socre=0.93 means 93% and accuracy = 0.88 means 88%, DecisionTreeClassifier using Gini Index(max depth)

In [73]:
#min_samples_leaf: inbuilt parameter of DecisionTreeClassifier class
#it is second pruning technique,leaf means no child
#value of min_samples_leaf parameter for any dataset >=45 and <=100
'''for i in range (45,101): #start=45 stop=101-1=100 step=+1
    #create object of DecisionTreeClassifier class and passing the parametr\er min_samples_leaf
    dtc1=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)
    #i=1 then i=2 etc
    #by default use method gini index
    print("\nMin_samples_leaf: ",i)
    #call user defined function
    dtc1=create_model(dtc1)'''

'for i in range (45,101): #start=45 stop=101-1=100 step=+1\n    #create object of DecisionTreeClassifier class and passing the parametr\\er min_samples_leaf\n    dtc1=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)\n    #i=1 then i=2 etc\n    #by default use method gini index\n    print("\nMin_samples_leaf: ",i)\n    #call user defined function\n    dtc1=create_model(dtc1)'

In [74]:
#create the object of DecisionTreeClassifier class and passing the parameter min_samples_leaf=63
dtc2=DecisionTreeClassifier(random_state=1,min_samples_leaf=63)
#call user defined function
dtc2=create_model(dtc2)

[[ 9345  1572]
 [  908 10009]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.88     10917
           1       0.86      0.92      0.89     10917

    accuracy                           0.89     21834
   macro avg       0.89      0.89      0.89     21834
weighted avg       0.89      0.89      0.89     21834



In [75]:
#create a dataframe
dict={"input columns": X.columns, "IG": dtc2.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by="IG", ascending=False, ignore_index=True)

input columns        IG
0         duration  0.520311
1      nr.employed  0.242409
2        euribor3m  0.113439
3    cons.conf.idx  0.034988
4            month  0.020023
5              age  0.017776
6      day_of_week  0.012571
7            pdays  0.010475
8   cons.price.idx  0.005377
9        education  0.005098
10        campaign  0.003676
11         housing  0.003044
12             job  0.002871
13        previous  0.002584
14         contact  0.002170
15        poutcome  0.001586
16         marital  0.001500
17            loan  0.000104
18    emp.var.rate  0.000000
19         default  0.000000

In [76]:
#in above report, recall socre=0.92 means 92% and accuracy = 0.89 means 89%, DecisionTreeClassifier using Gini Index(min samples leaf)

In [77]:
#use entropy method
#create object
dtc1=DecisionTreeClassifier(random_state=1,criterion='entropy')

In [78]:
#call function
dtc1=create_model(dtc1)

[[10256   661]
 [ 5392  5525]]
              precision    recall  f1-score   support

           0       0.66      0.94      0.77     10917
           1       0.89      0.51      0.65     10917

    accuracy                           0.72     21834
   macro avg       0.77      0.72      0.71     21834
weighted avg       0.77      0.72      0.71     21834



In [79]:
#create a df 
dict={'input columns':X.columns,'IG':dtc.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by='IG',ascending=False,ignore_index=True)

input columns        IG
0         duration  0.440809
1      nr.employed  0.177071
2        euribor3m  0.074209
3              age  0.063784
4     emp.var.rate  0.038670
5    cons.conf.idx  0.030706
6      day_of_week  0.026089
7              job  0.023265
8        education  0.022763
9         campaign  0.021767
10           month  0.018673
11         marital  0.011119
12         housing  0.011050
13           pdays  0.010653
14  cons.price.idx  0.009403
15        previous  0.007196
16            loan  0.005444
17         contact  0.004051
18        poutcome  0.003277
19         default  0.000000

In [80]:
#in decisiontreeclassifier,we got less  score0.51 means 51% reason behind the less score,model is overfit
#so we reduce overfiting the model, then use pruning technique of DecisionTreeClassifier class
#how to reduce overfitting situation by using the pruning technique:
#  1: max_dept: inbuilt parameter of DecisionTreeClassifier class
#  2.min_samples_leaf: inbuilt parameter of DecisionTreeClassifier class

In [81]:
#max_dept: inbuilt parameter of DecisionTreeClassifier class
#value of max_depth parameter for any dataset<=8
'''for i in range (1,9): #start=1 stop=9-1=8 step=+1
    #create object of DecisionTreeClassifier class and passing the parametrer max_dept
    dtc1=DecisionTreeClassifier(random_state=1,criterion='entropy',max_depth=i)
    #i=1 then i=2 etc
    #by default use method gini index
    print("\nMax depth: ",i)
    #call user defined function
    dtc1=create_model(dtc1)'''

'for i in range (1,9): #start=1 stop=9-1=8 step=+1\n    #create object of DecisionTreeClassifier class and passing the parametrer max_dept\n    dtc1=DecisionTreeClassifier(random_state=1,criterion=\'entropy\',max_depth=i)\n    #i=1 then i=2 etc\n    #by default use method gini index\n    print("\nMax depth: ",i)\n    #call user defined function\n    dtc1=create_model(dtc1)'

In [82]:
#create the object of DecisionTreeClassifier class and passing the parameter max_depth=5
dtc1=DecisionTreeClassifier(random_state=1,criterion='entropy',max_depth=5)
#by default use method gini index
#call user defined function
dtc1=create_model(dtc1)

[[ 9026  1891]
 [  884 10033]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87     10917
           1       0.84      0.92      0.88     10917

    accuracy                           0.87     21834
   macro avg       0.88      0.87      0.87     21834
weighted avg       0.88      0.87      0.87     21834



In [83]:
#create a df 
dict={'input columns':X.columns,'IG':dtc1.feature_importances_}   #IG means information gain of each input
df1=pd.DataFrame(dict)
df1.sort_values(by='IG',ascending=False,ignore_index=True)

input columns        IG
0         duration  0.517963
1      nr.employed  0.291380
2    cons.conf.idx  0.076483
3     emp.var.rate  0.062732
4            month  0.019126
5        euribor3m  0.016354
6            pdays  0.011789
7   cons.price.idx  0.003500
8         previous  0.000492
9         campaign  0.000180
10             job  0.000000
11         marital  0.000000
12        poutcome  0.000000
13     day_of_week  0.000000
14         contact  0.000000
15            loan  0.000000
16         housing  0.000000
17         default  0.000000
18       education  0.000000
19             age  0.000000

In [84]:
#in above report, recall socre=0.92 means 92% and accuracy = 0.87 means 87%, DecisionTreeClassifier using Entropy Method(max depth)

In [85]:
#min_samples_leaf: inbuilt parameter of DecisionTreeClassifier class
#it is second pruning technique,leaf means no child
#value of min_samples_leaf parameter for any dataset >=45 and <=100
'''for i in range (45,101): #start=45 stop=101-1=100 step=+1
    #create object of DecisionTreeClassifier class and passing the parameter min_samples_leaf
    dtc1=DecisionTreeClassifier(random_state=1,criterion='entropy',min_samples_leaf=i)
    #i=1 then i=2 etc
    #by default use method gini index
    print("\nMin_samples_leaf: ",i)
    #call user defined function
    dtc1=create_model(dtc1)'''

'for i in range (45,101): #start=45 stop=101-1=100 step=+1\n    #create object of DecisionTreeClassifier class and passing the parameter min_samples_leaf\n    dtc1=DecisionTreeClassifier(random_state=1,criterion=\'entropy\',min_samples_leaf=i)\n    #i=1 then i=2 etc\n    #by default use method gini index\n    print("\nMin_samples_leaf: ",i)\n    #call user defined function\n    dtc1=create_model(dtc1)'

In [86]:
#create the object of DecisionTreeClassifier class and passing the parameter min_samples_leaf=99
dtc2=DecisionTreeClassifier(random_state=1,criterion='entropy',min_samples_leaf=99)
#call user defined function
dtc2=create_model(dtc2)

[[ 9343  1574]
 [  816 10101]]
              precision    recall  f1-score   support

           0       0.92      0.86      0.89     10917
           1       0.87      0.93      0.89     10917

    accuracy                           0.89     21834
   macro avg       0.89      0.89      0.89     21834
weighted avg       0.89      0.89      0.89     21834



In [87]:
#create a dataframe
dict={"input columns": X.columns, "IG": dtc2.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by="IG", ascending=False, ignore_index=True)

input columns        IG
0         duration  0.465496
1      nr.employed  0.243887
2        euribor3m  0.074161
3    cons.conf.idx  0.071512
4     emp.var.rate  0.052488
5            month  0.017042
6      day_of_week  0.016376
7              age  0.016173
8            pdays  0.009864
9        education  0.005841
10        campaign  0.005549
11  cons.price.idx  0.004744
12        previous  0.004502
13         marital  0.003282
14         contact  0.002920
15             job  0.002632
16            loan  0.001358
17        poutcome  0.001185
18         housing  0.000987
19         default  0.000000

In [88]:
#in above report, recall socre=0.93 means 93% and accuracy = 0.89 means 89%, DecisionTreeClassifier using Entropy Method(min samples leaf)

In [89]:
#Apply Ensembling Technique

#1.BootStraping method:
#RandomForestTree(use Bagging):

from sklearn.ensemble import RandomForestClassifier


In [90]:
#Randamforest classifier  inbuil inner class
'''for i in range(10,101):
    rfc=RandomForestClassifier(n_estimators=i,random_state=1)
    print('No. of estimators means no. of Decision tree :',i)
    rfc=create_model(rfc)'''

"for i in range(10,101):\n    rfc=RandomForestClassifier(n_estimators=i,random_state=1)\n    print('No. of estimators means no. of Decision tree :',i)\n    rfc=create_model(rfc)"

In [91]:
 rfc=RandomForestClassifier(n_estimators=37,random_state=1)
 rfc=create_model(rfc)

[[10314   603]
 [ 3984  6933]]
              precision    recall  f1-score   support

           0       0.72      0.94      0.82     10917
           1       0.92      0.64      0.75     10917

    accuracy                           0.79     21834
   macro avg       0.82      0.79      0.78     21834
weighted avg       0.82      0.79      0.78     21834



In [92]:
#create a dataframe
dict={"input columns": X.columns, "IG": rfc.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by="IG", ascending=False, ignore_index=True)

input columns            IG
0         duration  4.166227e-01
1        euribor3m  9.936156e-02
2      nr.employed  7.761961e-02
3              age  6.261613e-02
4     emp.var.rate  5.744127e-02
5    cons.conf.idx  3.228861e-02
6              job  3.225605e-02
7         campaign  2.983584e-02
8        education  2.973832e-02
9      day_of_week  2.692070e-02
10  cons.price.idx  2.271293e-02
11           pdays  2.148998e-02
12        poutcome  1.932100e-02
13           month  1.746374e-02
14         marital  1.573486e-02
15         housing  1.169722e-02
16        previous  1.013625e-02
17         contact  8.608141e-03
18            loan  8.135063e-03
19         default  2.354868e-08

In [93]:
#In above report, recall score = 0.64 means 64% and Accuracy = 0.79 means 79%, using RandomForestClassifier

In [94]:
#Apply Next Ensembling Technique on same dataset 
#ADA Boost
#in adaptor boosting : create decision stump. Decision stump means one root node and 2 childs
#inbuilt class AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

In [95]:
'''for i in range(1,17):
    #create the object of class AdaBoostClassifier
    ada=AdaBoostClassifier(n_estimators=i,random_state=1)
    print("No of Estimator :",i)
    
    #call user defined function
    ada=create_model(ada)'''

'for i in range(1,17):\n    #create the object of class AdaBoostClassifier\n    ada=AdaBoostClassifier(n_estimators=i,random_state=1)\n    print("No of Estimator :",i)\n    \n    #call user defined function\n    ada=create_model(ada)'

In [96]:
#create the object of class AdaBoostClassifier
ada=AdaBoostClassifier(n_estimators=13,random_state=1)
#call user defined function
ada=create_model(ada)

[[9315 1602]
 [1254 9663]]
              precision    recall  f1-score   support

           0       0.88      0.85      0.87     10917
           1       0.86      0.89      0.87     10917

    accuracy                           0.87     21834
   macro avg       0.87      0.87      0.87     21834
weighted avg       0.87      0.87      0.87     21834



In [97]:
#create a dataframe
dict={"input columns": X.columns, "IG": ada.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by="IG", ascending=False, ignore_index=True)

input columns        IG
0         duration  0.461538
1    cons.conf.idx  0.153846
2      nr.employed  0.076923
3        euribor3m  0.076923
4   cons.price.idx  0.076923
5     emp.var.rate  0.076923
6            pdays  0.076923
7          marital  0.000000
8         previous  0.000000
9         campaign  0.000000
10             job  0.000000
11        poutcome  0.000000
12     day_of_week  0.000000
13           month  0.000000
14         contact  0.000000
15            loan  0.000000
16         housing  0.000000
17         default  0.000000
18       education  0.000000
19             age  0.000000

In [98]:
#In above report, recall score = 0.89 means 89% and Accuracy = 0.87 means 87%, using AdaBoostClassifier

In [99]:
#2.Gradient Boosting (GB):

from sklearn.ensemble import GradientBoostingClassifier

In [100]:
'''for i in range(10,101):
    #create the object of class GradientBoostingClassifier
    gbc=GradientBoostingClassifier(n_estimators=i,random_state=1)
    print("No of Estimator :",i)
    
    #call user defined function
    gbc=create_model(gbc)'''

'for i in range(10,101):\n    #create the object of class GradientBoostingClassifier\n    gbc=GradientBoostingClassifier(n_estimators=i,random_state=1)\n    print("No of Estimator :",i)\n    \n    #call user defined function\n    gbc=create_model(gbc)'

In [101]:
#create the object of class GradientBoostingClassifier
gbc=GradientBoostingClassifier(n_estimators=15,random_state=1)
#call user defined function
gbc=create_model(gbc)

[[ 8927  1990]
 [  787 10130]]
              precision    recall  f1-score   support

           0       0.92      0.82      0.87     10917
           1       0.84      0.93      0.88     10917

    accuracy                           0.87     21834
   macro avg       0.88      0.87      0.87     21834
weighted avg       0.88      0.87      0.87     21834



In [102]:
#create a dataframe
dict={"input columns": X.columns, "IG": gbc.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by="IG", ascending=False, ignore_index=True)

input columns        IG
0         duration  0.544806
1      nr.employed  0.291497
2        euribor3m  0.073571
3    cons.conf.idx  0.055725
4     emp.var.rate  0.009421
5   cons.price.idx  0.008625
6            pdays  0.008571
7            month  0.006194
8              age  0.000846
9         campaign  0.000404
10         contact  0.000339
11        poutcome  0.000000
12         marital  0.000000
13     day_of_week  0.000000
14        previous  0.000000
15            loan  0.000000
16         housing  0.000000
17         default  0.000000
18       education  0.000000
19             job  0.000000

In [103]:
#In above report, recall score = 0.93 means 93% and Accuracy = 0.87 means 87%, GradientBoostingClassifier

In [104]:
#Extreme Gradient Boost
#!pip install xgboost

In [105]:
from xgboost import XGBClassifier

In [106]:
'''for i in range(10,101):
    #create the object of class XGBClassifier
    xgbc=XGBClassifier(n_estimators=i,reg_alpha=1,random_state=1)
    print("No of Estimator :",i)
    
    #call user defined function
    xgbc=create_model(xgbc)'''

'for i in range(10,101):\n    #create the object of class XGBClassifier\n    xgbc=XGBClassifier(n_estimators=i,reg_alpha=1,random_state=1)\n    print("No of Estimator :",i)\n    \n    #call user defined function\n    xgbc=create_model(xgbc)'

In [107]:
#create the object of class XGBClassifier
xgbc=XGBClassifier(n_estimators=10,reg_alpha=1,random_state=1)   
#call user defined function
xgbc=create_model(xgbc)

[[ 9267  1650]
 [  779 10138]]
              precision    recall  f1-score   support

           0       0.92      0.85      0.88     10917
           1       0.86      0.93      0.89     10917

    accuracy                           0.89     21834
   macro avg       0.89      0.89      0.89     21834
weighted avg       0.89      0.89      0.89     21834



In [108]:
#create a dataframe
dict={"input columns": X.columns, "IG": xgbc.feature_importances_}
df1=pd.DataFrame(dict)
df1.sort_values(by="IG", ascending=False, ignore_index=True)

input columns        IG
0      nr.employed  0.494810
1         duration  0.136809
2     emp.var.rate  0.107841
3    cons.conf.idx  0.082795
4        euribor3m  0.041908
5            month  0.028486
6            pdays  0.017084
7          contact  0.012467
8   cons.price.idx  0.011787
9        education  0.010967
10        poutcome  0.009796
11     day_of_week  0.009702
12             age  0.007781
13            loan  0.007566
14        previous  0.006460
15             job  0.004214
16        campaign  0.004099
17         housing  0.003125
18         marital  0.002302
19         default  0.000000

In [109]:
#in above report, recall socre=0.93 means 93% and accuracy = 0.89 means 89%, Extreme Gradient Boost

In [110]:
#SVM
#1.use Linear Kernel Function
#use LinearSVC:


from sklearn.svm import LinearSVC

In [111]:
svc=LinearSVC(random_state=1) #create object 
#hard margin bydefault

In [112]:
svc=create_model(svc) #call function

[[9270 1647]
 [1421 9496]]
              precision    recall  f1-score   support

           0       0.87      0.85      0.86     10917
           1       0.85      0.87      0.86     10917

    accuracy                           0.86     21834
   macro avg       0.86      0.86      0.86     21834
weighted avg       0.86      0.86      0.86     21834



In [113]:
#In above report, recall score = 0.87 means 87% and Accuracy = 0.86 means 86%, LinearSVC(Hard Margin)


In [114]:
#Here score is good but not better, behind the reason, may be model is overfit means both classes are separate with straight line
#but may be model is overfit, so reduced overfit of model we add external error on training time and this process is known as 
#softmargin

In [115]:
#create object of class LinearSVC(softmargin)
svc1=LinearSVC(random_state=1, C=0.0001)

In [116]:
#call function
svc1=create_model(svc1)

[[9116 1801]
 [1405 9512]]
              precision    recall  f1-score   support

           0       0.87      0.84      0.85     10917
           1       0.84      0.87      0.86     10917

    accuracy                           0.85     21834
   macro avg       0.85      0.85      0.85     21834
weighted avg       0.85      0.85      0.85     21834



In [117]:
#In above report, recall score = 0.87 means 87% and Accuracy = 0.85 means 85%, LinearSVC(soft margin)

In [118]:
#no changes in score when add external error on training time means data is non-linear data
#use Non linear kernel function:

In [119]:
# polynomial kernel function:
'''it increase the dimension means its converts low dimension to high dimension.
suppose we have 1D  then it convert into 2D and so on.
use inbuilt class svc for non linear kernal function : polynomial or radial basis kernal function'''


from sklearn.svm import SVC

poly_svc=SVC(random_state=1,kernel='poly')  #create the object

In [120]:
poly_svc=create_model(poly_svc)

[[9354 1563]
 [1359 9558]]
              precision    recall  f1-score   support

           0       0.87      0.86      0.86     10917
           1       0.86      0.88      0.87     10917

    accuracy                           0.87     21834
   macro avg       0.87      0.87      0.87     21834
weighted avg       0.87      0.87      0.87     21834



In [121]:
#In above report, recall score = 0.88 means 88% and Accuracy = 0.87 means 87%, SVC(Polynomial Kernal function)

In [122]:
#create object of SVC for radial basis
svc_radial=SVC(random_state=1, kernel='rbf')

svc_radial=create_model(svc_radial)

[[9183 1734]
 [ 936 9981]]
              precision    recall  f1-score   support

           0       0.91      0.84      0.87     10917
           1       0.85      0.91      0.88     10917

    accuracy                           0.88     21834
   macro avg       0.88      0.88      0.88     21834
weighted avg       0.88      0.88      0.88     21834



In [123]:
#In above report, recall score = 0.91 means 91% and Accuracy = 0.88 means 88%, SVC(Radial basis function)

In [124]:
#In this dataset, we got best score by Extreme Gradient Boost.
#recall socre=0.93 means 93% and accuracy = 0.89 means 89%

Save Model


In [125]:
import pickle


In [126]:
#To open file in write binary for model create
file1=open("model.pkl","wb")  #model.pkl: new file which sotre object of algorithm which got highest score

#To open file in write binary for scaling
file2=open("scale.pkl","wb")  #scale.pkl : new file which store the object of StandardScaler class 

#To open file in write binary for LabelEncoder
file3 = open("label.pkl","wb")  #label.pkl : new file which store the object of LabelEncoder class

#file1, file2 and file3 are tempoary file


In [127]:
#save object of Algorithm (extrem gradient boost) class in temp file file1
#use inbuilt methodd dump() which method define in pickle class
pickle.dump(xgbc,file1) #syntax - pickle.dump(object of algorithm,temp file)
#to close temp file file1
file1.close()



In [128]:
#save object of StandardSclaer class
pickle.dump(ss,file2)
#to close temp file file2
file2.close()

In [129]:
#save object of LabelEncoder class
pickle.dump(le,file3)
#to close temp file file3
file3.close()